"""DOC099 — [FILL] placeholder marker not replaced.

Fires when the raw docstring text contains a [FILL] marker, indicating
that a stub generated by DOC001's fix has not been completed. Stubs
cannot pass the pipeline unmodified.
"""

from __future__ import annotations

import re
from typing import TYPE_CHECKING

from docpact.model.diagnostic import RuleResult, Severity, SourceLocation
from docpact.rules._registry import RuleConfig, RuleMetadata, register

if TYPE_CHECKING:
    from docpact.model.function_info import FunctionInfo
    from docpact.model.parsed_docstring import ParsedDocstring

_FILL_RE = re.compile(r"\[FILL")


@register(
    RuleMetadata(
        code="DOC099",
        namespace="DOC",
        summary="[FILL] placeholder marker not replaced",
        default_severity=Severity.ERROR,
        fixable=False,
        unsafe_fixable=False,
    )
)
def check(
    func: FunctionInfo,
    doc: ParsedDocstring | None,
    config: RuleConfig,
) -> list[RuleResult]:
    """Check that no stub placeholder markers remain in the docstring.

    Args:
        func: The function being checked.
        doc: Parsed docstring, or None if absent.
        config: Rule configuration including severity and tier.

    Returns:
        List with one DOC099 diagnostic when a placeholder marker is found.
    """
    if doc is None:
        return []
    if not _FILL_RE.search(doc.raw):
        return []
    return [
        RuleResult(
            code="DOC099",
            severity=config.severity,
            message="Docstring contains unfilled [FILL] placeholder",
            location=SourceLocation(
                file_path=func.file_path,
                line=func.line,
                column=func.column,
            ),
        )
    ]
